// ── Local Food Database ──
// Based on USDA FoodData Central public domain nutritional data.
// Per-serving values. No external API needed.

const FOOD_DB = [
  // ═══════════════════════ FRUITS ═══════════════════════
  { name: 'Apple (medium)', category: 'Fruits', serving: '1 medium (182g)', calories: 95, protein: 0, carbs: 25, fat: 0, fiber: 4, sugar: 19, color: 'green' },
  { name: 'Banana (medium)', category: 'Fruits', serving: '1 medium (118g)', calories: 105, protein: 1, carbs: 27, fat: 0, fiber: 3, sugar: 14, color: 'green' },
  { name: 'Orange (medium)', category: 'Fruits', serving: '1 medium (131g)', calories: 62, protein: 1, carbs: 15, fat: 0, fiber: 3, sugar: 12, color: 'green' },
  { name: 'Strawberries', category: 'Fruits', serving: '1 cup (152g)', calories: 49, protein: 1, carbs: 12, fat: 0, fiber: 3, sugar: 7, color: 'green' },
  { name: 'Blueberries', category: 'Fruits', serving: '1 cup (148g)', calories: 84, protein: 1, carbs: 21, fat: 0, fiber: 4, sugar: 15, color: 'green' },
  { name: 'Raspberries', category: 'Fruits', serving: '1 cup (123g)', calories: 64, protein: 1, carbs: 15, fat: 1, fiber: 8, sugar: 5, color: 'green' },
  { name: 'Grapes (seedless)', category: 'Fruits', serving: '1 cup (151g)', calories: 104, protein: 1, carbs: 27, fat: 0, fiber: 1, sugar: 23, color: 'green' },
  { name: 'Watermelon', category: 'Fruits', serving: '1 cup diced (152g)', calories: 46, protein: 1, carbs: 12, fat: 0, fiber: 1, sugar: 9, color: 'green' },
  { name: 'Pineapple', category: 'Fruits', serving: '1 cup chunks (165g)', calories: 82, protein: 1, carbs: 22, fat: 0, fiber: 2, sugar: 16, color: 'green' },
  { name: 'Mango', category: 'Fruits', serving: '1 cup sliced (165g)', calories: 99, protein: 1, carbs: 25, fat: 1, fiber: 3, sugar: 23, color: 'green' },
  { name: 'Peach (medium)', category: 'Fruits', serving: '1 medium (150g)', calories: 59, protein: 1, carbs: 14, fat: 0, fiber: 2, sugar: 13, color: 'green' },
  { name: 'Pear (medium)', category: 'Fruits', serving: '1 medium (178g)', calories: 101, protein: 1, carbs: 27, fat: 0, fiber: 6, sugar: 17, color: 'green' },
  { name: 'Cherries (sweet)', category: 'Fruits', serving: '1 cup (138g)', calories: 87, protein: 1, carbs: 22, fat: 0, fiber: 3, sugar: 18, color: 'green' },
  { name: 'Kiwi', category: 'Fruits', serving: '1 medium (69g)', calories: 42, protein: 1, carbs: 10, fat: 0, fiber: 2, sugar: 6, color: 'green' },
  { name: 'Grapefruit (half)', category: 'Fruits', serving: '1/2 medium (123g)', calories: 52, protein: 1, carbs: 13, fat: 0, fiber: 2, sugar: 8, color: 'green' },
  { name: 'Cantaloupe', category: 'Fruits', serving: '1 cup cubed (160g)', calories: 54, protein: 1, carbs: 13, fat: 0, fiber: 1, sugar: 13, color: 'green' },
  { name: 'Avocado', category: 'Fruits', serving: '1/2 medium (68g)', calories: 114, protein: 1, carbs: 6, fat: 10, fiber: 5, sugar: 0, color: 'green' },
  { name: 'Pomegranate seeds', category: 'Fruits', serving: '1/2 cup (87g)', calories: 72, protein: 1, carbs: 16, fat: 1, fiber: 3, sugar: 12, color: 'green' },
  { name: 'Dried cranberries', category: 'Fruits', serving: '1/4 cup (40g)', calories: 123, protein: 0, carbs: 33, fat: 1, fiber: 2, sugar: 29, color: 'yellow' },
  { name: 'Raisins', category: 'Fruits', serving: '1/4 cup (41g)', calories: 123, protein: 1, carbs: 33, fat: 0, fiber: 2, sugar: 25, color: 'yellow' },
  { name: 'Dates (Medjool)', category: 'Fruits', serving: '2 dates (48g)', calories: 133, protein: 1, carbs: 36, fat: 0, fiber: 3, sugar: 32, color: 'yellow' },

  // ═══════════════════════ VEGETABLES ═══════════════════════
  { name: 'Broccoli (steamed)', category: 'Vegetables', serving: '1 cup (156g)', calories: 55, protein: 4, carbs: 11, fat: 1, fiber: 5, sugar: 2, color: 'green' },
  { name: 'Spinach (raw)', category: 'Vegetables', serving: '2 cups (60g)', calories: 14, protein: 2, carbs: 2, fat: 0, fiber: 1, sugar: 0, color: 'green' },
  { name: 'Kale (raw)', category: 'Vegetables', serving: '1 cup chopped (67g)', calories: 33, protein: 3, carbs: 6, fat: 1, fiber: 1, sugar: 2, color: 'green' },
  { name: 'Carrot (medium)', category: 'Vegetables', serving: '1 medium (61g)', calories: 25, protein: 1, carbs: 6, fat: 0, fiber: 2, sugar: 3, color: 'green' },
  { name: 'Sweet Potato (baked)', category: 'Vegetables', serving: '1 medium (114g)', calories: 103, protein: 2, carbs: 24, fat: 0, fiber: 4, sugar: 7, color: 'green' },
  { name: 'Bell Pepper (red)', category: 'Vegetables', serving: '1 medium (119g)', calories: 31, protein: 1, carbs: 6, fat: 0, fiber: 2, sugar: 4, color: 'green' },
  { name: 'Tomato (medium)', category: 'Vegetables', serving: '1 medium (123g)', calories: 22, protein: 1, carbs: 5, fat: 0, fiber: 2, sugar: 3, color: 'green' },
  { name: 'Cucumber', category: 'Vegetables', serving: '1/2 medium (150g)', calories: 23, protein: 1, carbs: 4, fat: 0, fiber: 1, sugar: 3, color: 'green' },
  { name: 'Zucchini', category: 'Vegetables', serving: '1 cup sliced (113g)', calories: 19, protein: 1, carbs: 4, fat: 0, fiber: 1, sugar: 3, color: 'green' },
  { name: 'Cauliflower', category: 'Vegetables', serving: '1 cup (107g)', calories: 27, protein: 2, carbs: 5, fat: 0, fiber: 2, sugar: 2, color: 'green' },
  { name: 'Green Beans (steamed)', category: 'Vegetables', serving: '1 cup (125g)', calories: 44, protein: 2, carbs: 10, fat: 0, fiber: 4, sugar: 4, color: 'green' },
  { name: 'Asparagus', category: 'Vegetables', serving: '6 spears (90g)', calories: 20, protein: 2, carbs: 4, fat: 0, fiber: 2, sugar: 1, color: 'green' },
  { name: 'Brussels Sprouts', category: 'Vegetables', serving: '1 cup (88g)', calories: 38, protein: 3, carbs: 8, fat: 0, fiber: 3, sugar: 2, color: 'green' },
  { name: 'Mushrooms (white)', category: 'Vegetables', serving: '1 cup sliced (70g)', calories: 15, protein: 2, carbs: 2, fat: 0, fiber: 1, sugar: 1, color: 'green' },
  { name: 'Celery', category: 'Vegetables', serving: '2 stalks (80g)', calories: 13, protein: 1, carbs: 2, fat: 0, fiber: 1, sugar: 1, color: 'green' },
  { name: 'Corn on the Cob', category: 'Vegetables', serving: '1 medium ear (90g)', calories: 88, protein: 3, carbs: 19, fat: 1, fiber: 2, sugar: 5, color: 'green' },
  { name: 'Onion (chopped)', category: 'Vegetables', serving: '1/2 cup (80g)', calories: 32, protein: 1, carbs: 7, fat: 0, fiber: 1, sugar: 3, color: 'green' },
  { name: 'Edamame', category: 'Vegetables', serving: '1 cup shelled (155g)', calories: 188, protein: 18, carbs: 14, fat: 8, fiber: 8, sugar: 3, color: 'green' },
  { name: 'Beets (cooked)', category: 'Vegetables', serving: '1 cup sliced (170g)', calories: 75, protein: 3, carbs: 17, fat: 0, fiber: 3, sugar: 14, color: 'green' },
  { name: 'Artichoke (medium)', category: 'Vegetables', serving: '1 medium (120g)', calories: 60, protein: 4, carbs: 13, fat: 0, fiber: 7, sugar: 1, color: 'green' },

  // ═══════════════════════ GRAINS & BREAD ═══════════════════════
  { name: 'White Rice (cooked)', category: 'Grains', serving: '1 cup (186g)', calories: 206, protein: 4, carbs: 45, fat: 0, fiber: 1, sugar: 0, color: 'yellow' },
  { name: 'Brown Rice (cooked)', category: 'Grains', serving: '1 cup (195g)', calories: 216, protein: 5, carbs: 45, fat: 2, fiber: 4, sugar: 1, color: 'green' },
  { name: 'Quinoa (cooked)', category: 'Grains', serving: '1 cup (185g)', calories: 222, protein: 8, carbs: 39, fat: 4, fiber: 5, sugar: 2, color: 'green' },
  { name: 'Whole Wheat Bread', category: 'Grains', serving: '1 slice (28g)', calories: 69, protein: 4, carbs: 12, fat: 1, fiber: 2, sugar: 1, color: 'green' },
  { name: 'White Bread', category: 'Grains', serving: '1 slice (25g)', calories: 67, protein: 2, carbs: 13, fat: 1, fiber: 1, sugar: 1, color: 'yellow' },
  { name: 'Sourdough Bread', category: 'Grains', serving: '1 slice (36g)', calories: 93, protein: 4, carbs: 18, fat: 1, fiber: 1, sugar: 1, color: 'yellow' },
  { name: 'Oatmeal (cooked)', category: 'Grains', serving: '1 cup (234g)', calories: 154, protein: 6, carbs: 27, fat: 3, fiber: 4, sugar: 1, color: 'green' },
  { name: 'Rolled Oats (dry)', category: 'Grains', serving: '1/2 cup (40g)', calories: 150, protein: 5, carbs: 27, fat: 3, fiber: 4, sugar: 1, color: 'green' },
  { name: 'Spaghetti (cooked)', category: 'Grains', serving: '1 cup (140g)', calories: 220, protein: 8, carbs: 43, fat: 1, fiber: 3, sugar: 1, color: 'yellow' },
  { name: 'Whole Wheat Pasta (cooked)', category: 'Grains', serving: '1 cup (140g)', calories: 174, protein: 7, carbs: 37, fat: 1, fiber: 6, sugar: 1, color: 'green' },
  { name: 'Flour Tortilla (8")', category: 'Grains', serving: '1 tortilla (49g)', calories: 146, protein: 4, carbs: 24, fat: 4, fiber: 1, sugar: 1, color: 'yellow' },
  { name: 'Corn Tortilla (6")', category: 'Grains', serving: '1 tortilla (26g)', calories: 52, protein: 1, carbs: 11, fat: 1, fiber: 2, sugar: 0, color: 'green' },
  { name: 'Bagel (plain)', category: 'Grains', serving: '1 bagel (95g)', calories: 270, protein: 10, carbs: 53, fat: 2, fiber: 2, sugar: 6, color: 'yellow' },
  { name: 'English Muffin', category: 'Grains', serving: '1 muffin (57g)', calories: 132, protein: 5, carbs: 25, fat: 1, fiber: 2, sugar: 2, color: 'yellow' },
  { name: 'Pita Bread (whole wheat)', category: 'Grains', serving: '1 pita (64g)', calories: 170, protein: 6, carbs: 35, fat: 2, fiber: 5, sugar: 1, color: 'green' },
  { name: 'Granola', category: 'Grains', serving: '1/2 cup (61g)', calories: 298, protein: 7, carbs: 32, fat: 15, fiber: 4, sugar: 12, color: 'yellow' },
  { name: 'Couscous (cooked)', category: 'Grains', serving: '1 cup (157g)', calories: 176, protein: 6, carbs: 36, fat: 0, fiber: 2, sugar: 0, color: 'yellow' },
  { name: 'Farro (cooked)', category: 'Grains', serving: '1/2 cup (100g)', calories: 170, protein: 7, carbs: 34, fat: 2, fiber: 4, sugar: 0, color: 'green' },

  // ═══════════════════════ PROTEIN - MEAT & POULTRY ═══════════════════════
  { name: 'Chicken Breast (grilled)', category: 'Protein', serving: '4 oz (113g)', calories: 187, protein: 35, carbs: 0, fat: 4, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Chicken Thigh (skin-on)', category: 'Protein', serving: '1 thigh (116g)', calories: 229, protein: 28, carbs: 0, fat: 13, fiber: 0, sugar: 0, color: 'yellow' },
  { name: 'Ground Turkey (93% lean)', category: 'Protein', serving: '4 oz cooked (113g)', calories: 170, protein: 21, carbs: 0, fat: 9, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Ground Beef (90% lean)', category: 'Protein', serving: '4 oz cooked (113g)', calories: 200, protein: 22, carbs: 0, fat: 11, fiber: 0, sugar: 0, color: 'yellow' },
  { name: 'Ground Beef (80% lean)', category: 'Protein', serving: '4 oz cooked (113g)', calories: 286, protein: 19, carbs: 0, fat: 23, fiber: 0, sugar: 0, color: 'red' },
  { name: 'Sirloin Steak', category: 'Protein', serving: '4 oz cooked (113g)', calories: 207, protein: 31, carbs: 0, fat: 8, fiber: 0, sugar: 0, color: 'yellow' },
  { name: 'Ribeye Steak', category: 'Protein', serving: '4 oz cooked (113g)', calories: 310, protein: 26, carbs: 0, fat: 23, fiber: 0, sugar: 0, color: 'red' },
  { name: 'Pork Tenderloin', category: 'Protein', serving: '4 oz cooked (113g)', calories: 166, protein: 26, carbs: 0, fat: 6, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Pork Chop (boneless)', category: 'Protein', serving: '4 oz cooked (113g)', calories: 239, protein: 30, carbs: 0, fat: 13, fiber: 0, sugar: 0, color: 'yellow' },
  { name: 'Bacon', category: 'Protein', serving: '3 slices (34g)', calories: 161, protein: 12, carbs: 0, fat: 12, fiber: 0, sugar: 0, color: 'red' },
  { name: 'Turkey Bacon', category: 'Protein', serving: '3 slices (30g)', calories: 90, protein: 6, carbs: 0, fat: 7, fiber: 0, sugar: 0, color: 'yellow' },
  { name: 'Ham (deli sliced)', category: 'Protein', serving: '3 slices (56g)', calories: 60, protein: 10, carbs: 2, fat: 2, fiber: 0, sugar: 1, color: 'green' },
  { name: 'Turkey Breast (deli)', category: 'Protein', serving: '3 slices (56g)', calories: 54, protein: 11, carbs: 1, fat: 1, fiber: 0, sugar: 1, color: 'green' },
  { name: 'Italian Sausage', category: 'Protein', serving: '1 link (83g)', calories: 268, protein: 17, carbs: 3, fat: 21, fiber: 0, sugar: 1, color: 'red' },
  { name: 'Lamb Chop', category: 'Protein', serving: '4 oz cooked (113g)', calories: 250, protein: 26, carbs: 0, fat: 16, fiber: 0, sugar: 0, color: 'yellow' },

  // ═══════════════════════ PROTEIN - SEAFOOD ═══════════════════════
  { name: 'Salmon (wild, baked)', category: 'Seafood', serving: '4 oz (113g)', calories: 234, protein: 25, carbs: 0, fat: 14, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Tuna (canned in water)', category: 'Seafood', serving: '1 can drained (142g)', calories: 179, protein: 39, carbs: 0, fat: 1, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Shrimp (cooked)', category: 'Seafood', serving: '4 oz (113g)', calories: 112, protein: 24, carbs: 1, fat: 1, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Tilapia (baked)', category: 'Seafood', serving: '4 oz (113g)', calories: 145, protein: 30, carbs: 0, fat: 3, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Cod (baked)', category: 'Seafood', serving: '4 oz (113g)', calories: 119, protein: 26, carbs: 0, fat: 1, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Scallops (pan-seared)', category: 'Seafood', serving: '4 oz (113g)', calories: 111, protein: 21, carbs: 5, fat: 1, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Crab Meat', category: 'Seafood', serving: '4 oz (113g)', calories: 98, protein: 20, carbs: 0, fat: 2, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Lobster Tail', category: 'Seafood', serving: '1 tail (145g)', calories: 129, protein: 28, carbs: 0, fat: 1, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Sardines (canned in oil)', category: 'Seafood', serving: '1 can (92g)', calories: 208, protein: 25, carbs: 0, fat: 11, fiber: 0, sugar: 0, color: 'yellow' },
  { name: 'Sushi Salmon Roll', category: 'Seafood', serving: '6 pieces (174g)', calories: 304, protein: 13, carbs: 42, fat: 8, fiber: 1, sugar: 7, color: 'yellow' },

  // ═══════════════════════ EGGS & DAIRY ═══════════════════════
  { name: 'Egg (large, whole)', category: 'Dairy & Eggs', serving: '1 large (50g)', calories: 72, protein: 6, carbs: 0, fat: 5, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Egg Whites', category: 'Dairy & Eggs', serving: '3 whites (99g)', calories: 51, protein: 11, carbs: 1, fat: 0, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Hard Boiled Egg', category: 'Dairy & Eggs', serving: '1 large (50g)', calories: 78, protein: 6, carbs: 1, fat: 5, fiber: 0, sugar: 1, color: 'green' },
  { name: 'Greek Yogurt (plain, 2%)', category: 'Dairy & Eggs', serving: '3/4 cup (170g)', calories: 130, protein: 17, carbs: 8, fat: 4, fiber: 0, sugar: 7, color: 'green' },
  { name: 'Greek Yogurt (vanilla)', category: 'Dairy & Eggs', serving: '3/4 cup (170g)', calories: 150, protein: 15, carbs: 17, fat: 3, fiber: 0, sugar: 15, color: 'yellow' },
  { name: 'Regular Yogurt (low-fat)', category: 'Dairy & Eggs', serving: '1 cup (245g)', calories: 154, protein: 13, carbs: 17, fat: 4, fiber: 0, sugar: 17, color: 'yellow' },
  { name: 'Cottage Cheese (2%)', category: 'Dairy & Eggs', serving: '1/2 cup (113g)', calories: 92, protein: 12, carbs: 5, fat: 3, fiber: 0, sugar: 4, color: 'green' },
  { name: 'Milk (whole)', category: 'Dairy & Eggs', serving: '1 cup (244ml)', calories: 149, protein: 8, carbs: 12, fat: 8, fiber: 0, sugar: 12, color: 'yellow' },
  { name: 'Milk (2%)', category: 'Dairy & Eggs', serving: '1 cup (244ml)', calories: 122, protein: 8, carbs: 12, fat: 5, fiber: 0, sugar: 12, color: 'green' },
  { name: 'Milk (skim)', category: 'Dairy & Eggs', serving: '1 cup (244ml)', calories: 83, protein: 8, carbs: 12, fat: 0, fiber: 0, sugar: 12, color: 'green' },
  { name: 'Almond Milk (unsweetened)', category: 'Dairy & Eggs', serving: '1 cup (240ml)', calories: 30, protein: 1, carbs: 1, fat: 3, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Oat Milk', category: 'Dairy & Eggs', serving: '1 cup (240ml)', calories: 120, protein: 3, carbs: 16, fat: 5, fiber: 2, sugar: 7, color: 'green' },
  { name: 'Cheddar Cheese', category: 'Dairy & Eggs', serving: '1 oz (28g)', calories: 113, protein: 7, carbs: 0, fat: 9, fiber: 0, sugar: 0, color: 'yellow' },
  { name: 'Mozzarella (part-skim)', category: 'Dairy & Eggs', serving: '1 oz (28g)', calories: 72, protein: 7, carbs: 1, fat: 5, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Parmesan (grated)', category: 'Dairy & Eggs', serving: '2 tbsp (10g)', calories: 42, protein: 4, carbs: 0, fat: 3, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Cream Cheese', category: 'Dairy & Eggs', serving: '2 tbsp (29g)', calories: 99, protein: 2, carbs: 2, fat: 10, fiber: 0, sugar: 1, color: 'red' },
  { name: 'Feta Cheese', category: 'Dairy & Eggs', serving: '1 oz (28g)', calories: 75, protein: 4, carbs: 1, fat: 6, fiber: 0, sugar: 1, color: 'yellow' },
  { name: 'Swiss Cheese', category: 'Dairy & Eggs', serving: '1 slice (28g)', calories: 108, protein: 8, carbs: 2, fat: 8, fiber: 0, sugar: 1, color: 'yellow' },
  { name: 'Butter', category: 'Dairy & Eggs', serving: '1 tbsp (14g)', calories: 102, protein: 0, carbs: 0, fat: 12, fiber: 0, sugar: 0, color: 'red' },
  { name: 'Sour Cream', category: 'Dairy & Eggs', serving: '2 tbsp (30g)', calories: 60, protein: 1, carbs: 1, fat: 6, fiber: 0, sugar: 1, color: 'yellow' },

  // ═══════════════════════ LEGUMES & BEANS ═══════════════════════
  { name: 'Black Beans (cooked)', category: 'Legumes', serving: '1/2 cup (86g)', calories: 114, protein: 8, carbs: 20, fat: 0, fiber: 8, sugar: 0, color: 'green' },
  { name: 'Chickpeas (cooked)', category: 'Legumes', serving: '1/2 cup (82g)', calories: 134, protein: 7, carbs: 22, fat: 2, fiber: 6, sugar: 4, color: 'green' },
  { name: 'Lentils (cooked)', category: 'Legumes', serving: '1/2 cup (99g)', calories: 115, protein: 9, carbs: 20, fat: 0, fiber: 8, sugar: 2, color: 'green' },
  { name: 'Kidney Beans (cooked)', category: 'Legumes', serving: '1/2 cup (89g)', calories: 112, protein: 8, carbs: 20, fat: 0, fiber: 6, sugar: 0, color: 'green' },
  { name: 'Hummus', category: 'Legumes', serving: '2 tbsp (30g)', calories: 70, protein: 2, carbs: 4, fat: 5, fiber: 2, sugar: 0, color: 'green' },
  { name: 'Pinto Beans (cooked)', category: 'Legumes', serving: '1/2 cup (86g)', calories: 122, protein: 8, carbs: 22, fat: 1, fiber: 8, sugar: 0, color: 'green' },
  { name: 'Refried Beans', category: 'Legumes', serving: '1/2 cup (126g)', calories: 119, protein: 7, carbs: 20, fat: 2, fiber: 7, sugar: 1, color: 'green' },
  { name: 'Tofu (firm)', category: 'Legumes', serving: '1/2 cup (126g)', calories: 88, protein: 10, carbs: 2, fat: 5, fiber: 1, sugar: 1, color: 'green' },
  { name: 'Tempeh', category: 'Legumes', serving: '3 oz (85g)', calories: 162, protein: 15, carbs: 9, fat: 9, fiber: 0, sugar: 0, color: 'green' },

  // ═══════════════════════ NUTS & SEEDS ═══════════════════════
  { name: 'Almonds', category: 'Nuts & Seeds', serving: '1 oz (28g, ~23 nuts)', calories: 164, protein: 6, carbs: 6, fat: 14, fiber: 4, sugar: 1, color: 'yellow' },
  { name: 'Walnuts', category: 'Nuts & Seeds', serving: '1 oz (28g, ~14 halves)', calories: 185, protein: 4, carbs: 4, fat: 18, fiber: 2, sugar: 1, color: 'yellow' },
  { name: 'Cashews', category: 'Nuts & Seeds', serving: '1 oz (28g)', calories: 157, protein: 5, carbs: 9, fat: 12, fiber: 1, sugar: 2, color: 'yellow' },
  { name: 'Peanuts', category: 'Nuts & Seeds', serving: '1 oz (28g)', calories: 161, protein: 7, carbs: 5, fat: 14, fiber: 2, sugar: 1, color: 'yellow' },
  { name: 'Peanut Butter', category: 'Nuts & Seeds', serving: '2 tbsp (32g)', calories: 188, protein: 8, carbs: 6, fat: 16, fiber: 2, sugar: 3, color: 'yellow' },
  { name: 'Almond Butter', category: 'Nuts & Seeds', serving: '2 tbsp (32g)', calories: 196, protein: 7, carbs: 6, fat: 18, fiber: 3, sugar: 2, color: 'yellow' },
  { name: 'Pecans', category: 'Nuts & Seeds', serving: '1 oz (28g)', calories: 196, protein: 3, carbs: 4, fat: 20, fiber: 3, sugar: 1, color: 'yellow' },
  { name: 'Pistachios', category: 'Nuts & Seeds', serving: '1 oz (28g, ~49 nuts)', calories: 159, protein: 6, carbs: 8, fat: 13, fiber: 3, sugar: 2, color: 'yellow' },
  { name: 'Sunflower Seeds', category: 'Nuts & Seeds', serving: '1/4 cup (35g)', calories: 204, protein: 7, carbs: 7, fat: 18, fiber: 3, sugar: 1, color: 'yellow' },
  { name: 'Chia Seeds', category: 'Nuts & Seeds', serving: '2 tbsp (28g)', calories: 138, protein: 5, carbs: 12, fat: 9, fiber: 10, sugar: 0, color: 'green' },
  { name: 'Flaxseed (ground)', category: 'Nuts & Seeds', serving: '2 tbsp (14g)', calories: 74, protein: 3, carbs: 4, fat: 6, fiber: 4, sugar: 0, color: 'green' },
  { name: 'Pumpkin Seeds', category: 'Nuts & Seeds', serving: '1 oz (28g)', calories: 158, protein: 9, carbs: 3, fat: 14, fiber: 2, sugar: 0, color: 'yellow' },
  { name: 'Trail Mix', category: 'Nuts & Seeds', serving: '1/4 cup (38g)', calories: 173, protein: 5, carbs: 16, fat: 11, fiber: 2, sugar: 10, color: 'yellow' },

  // ═══════════════════════ SNACKS ═══════════════════════
  { name: 'Popcorn (air-popped)', category: 'Snacks', serving: '3 cups (24g)', calories: 93, protein: 3, carbs: 19, fat: 1, fiber: 4, sugar: 0, color: 'green' },
  { name: 'Popcorn (butter)', category: 'Snacks', serving: '3 cups (33g)', calories: 160, protein: 2, carbs: 19, fat: 9, fiber: 2, sugar: 0, color: 'yellow' },
  { name: 'Tortilla Chips', category: 'Snacks', serving: '1 oz (28g, ~12 chips)', calories: 142, protein: 2, carbs: 18, fat: 7, fiber: 1, sugar: 0, color: 'yellow' },
  { name: 'Potato Chips', category: 'Snacks', serving: '1 oz (28g, ~15 chips)', calories: 152, protein: 2, carbs: 15, fat: 10, fiber: 1, sugar: 0, color: 'red' },
  { name: 'Pretzels', category: 'Snacks', serving: '1 oz (28g)', calories: 108, protein: 3, carbs: 23, fat: 1, fiber: 1, sugar: 1, color: 'yellow' },
  { name: 'Rice Cakes', category: 'Snacks', serving: '2 cakes (18g)', calories: 70, protein: 1, carbs: 15, fat: 1, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Granola Bar', category: 'Snacks', serving: '1 bar (42g)', calories: 190, protein: 3, carbs: 29, fat: 7, fiber: 2, sugar: 12, color: 'yellow' },
  { name: 'Protein Bar', category: 'Snacks', serving: '1 bar (60g)', calories: 230, protein: 20, carbs: 22, fat: 8, fiber: 3, sugar: 6, color: 'yellow' },
  { name: 'Crackers (whole wheat)', category: 'Snacks', serving: '6 crackers (30g)', calories: 120, protein: 3, carbs: 20, fat: 4, fiber: 3, sugar: 0, color: 'green' },
  { name: 'Cheese Crackers', category: 'Snacks', serving: '27 crackers (30g)', calories: 150, protein: 3, carbs: 18, fat: 8, fiber: 1, sugar: 1, color: 'yellow' },
  { name: 'Dark Chocolate (70%+)', category: 'Snacks', serving: '1 oz (28g)', calories: 170, protein: 2, carbs: 13, fat: 12, fiber: 3, sugar: 7, color: 'yellow' },
  { name: 'Beef Jerky', category: 'Snacks', serving: '1 oz (28g)', calories: 116, protein: 9, carbs: 3, fat: 7, fiber: 0, sugar: 3, color: 'yellow' },

  // ═══════════════════════ BEVERAGES ═══════════════════════
  { name: 'Coffee (black)', category: 'Beverages', serving: '8 fl oz (237ml)', calories: 2, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Latte (whole milk)', category: 'Beverages', serving: '12 fl oz (354ml)', calories: 183, protein: 10, carbs: 14, fat: 10, fiber: 0, sugar: 14, color: 'yellow' },
  { name: 'Latte (oat milk)', category: 'Beverages', serving: '12 fl oz (354ml)', calories: 150, protein: 4, carbs: 22, fat: 5, fiber: 1, sugar: 10, color: 'yellow' },
  { name: 'Cappuccino (whole milk)', category: 'Beverages', serving: '8 fl oz (237ml)', calories: 80, protein: 5, carbs: 6, fat: 4, fiber: 0, sugar: 6, color: 'green' },
  { name: 'Green Tea', category: 'Beverages', serving: '8 fl oz (237ml)', calories: 2, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Orange Juice', category: 'Beverages', serving: '8 fl oz (248ml)', calories: 112, protein: 2, carbs: 26, fat: 0, fiber: 0, sugar: 21, color: 'yellow' },
  { name: 'Smoothie (fruit)', category: 'Beverages', serving: '12 fl oz (354ml)', calories: 230, protein: 3, carbs: 54, fat: 1, fiber: 4, sugar: 44, color: 'yellow' },
  { name: 'Protein Shake', category: 'Beverages', serving: '1 scoop + water (350ml)', calories: 120, protein: 24, carbs: 3, fat: 2, fiber: 1, sugar: 1, color: 'green' },
  { name: 'Coca-Cola', category: 'Beverages', serving: '12 fl oz (355ml)', calories: 140, protein: 0, carbs: 39, fat: 0, fiber: 0, sugar: 39, color: 'red' },
  { name: 'Diet Coke', category: 'Beverages', serving: '12 fl oz (355ml)', calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Beer (regular)', category: 'Beverages', serving: '12 fl oz (355ml)', calories: 153, protein: 2, carbs: 13, fat: 0, fiber: 0, sugar: 0, color: 'red' },
  { name: 'Beer (light)', category: 'Beverages', serving: '12 fl oz (355ml)', calories: 103, protein: 1, carbs: 6, fat: 0, fiber: 0, sugar: 0, color: 'yellow' },
  { name: 'Red Wine', category: 'Beverages', serving: '5 fl oz (148ml)', calories: 125, protein: 0, carbs: 4, fat: 0, fiber: 0, sugar: 1, color: 'yellow' },
  { name: 'White Wine', category: 'Beverages', serving: '5 fl oz (148ml)', calories: 121, protein: 0, carbs: 4, fat: 0, fiber: 0, sugar: 1, color: 'yellow' },
  { name: 'Kombucha', category: 'Beverages', serving: '8 fl oz (240ml)', calories: 30, protein: 0, carbs: 7, fat: 0, fiber: 0, sugar: 5, color: 'green' },

  // ═══════════════════════ CONDIMENTS & SAUCES ═══════════════════════
  { name: 'Olive Oil', category: 'Oils & Sauces', serving: '1 tbsp (14ml)', calories: 119, protein: 0, carbs: 0, fat: 14, fiber: 0, sugar: 0, color: 'yellow' },
  { name: 'Coconut Oil', category: 'Oils & Sauces', serving: '1 tbsp (14ml)', calories: 121, protein: 0, carbs: 0, fat: 14, fiber: 0, sugar: 0, color: 'red' },
  { name: 'Ketchup', category: 'Oils & Sauces', serving: '1 tbsp (17g)', calories: 20, protein: 0, carbs: 5, fat: 0, fiber: 0, sugar: 4, color: 'green' },
  { name: 'Mustard (yellow)', category: 'Oils & Sauces', serving: '1 tsp (5g)', calories: 3, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Mayonnaise', category: 'Oils & Sauces', serving: '1 tbsp (13g)', calories: 94, protein: 0, carbs: 0, fat: 10, fiber: 0, sugar: 0, color: 'red' },
  { name: 'Ranch Dressing', category: 'Oils & Sauces', serving: '2 tbsp (30ml)', calories: 129, protein: 0, carbs: 2, fat: 13, fiber: 0, sugar: 1, color: 'red' },
  { name: 'Balsamic Vinaigrette', category: 'Oils & Sauces', serving: '2 tbsp (30ml)', calories: 90, protein: 0, carbs: 4, fat: 8, fiber: 0, sugar: 3, color: 'yellow' },
  { name: 'Soy Sauce', category: 'Oils & Sauces', serving: '1 tbsp (18ml)', calories: 9, protein: 1, carbs: 1, fat: 0, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Teriyaki Sauce', category: 'Oils & Sauces', serving: '1 tbsp (18ml)', calories: 16, protein: 1, carbs: 3, fat: 0, fiber: 0, sugar: 3, color: 'green' },
  { name: 'Hot Sauce', category: 'Oils & Sauces', serving: '1 tsp (5ml)', calories: 1, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, color: 'green' },
  { name: 'Salsa', category: 'Oils & Sauces', serving: '2 tbsp (30g)', calories: 10, protein: 0, carbs: 2, fat: 0, fiber: 0, sugar: 1, color: 'green' },
  { name: 'BBQ Sauce', category: 'Oils & Sauces', serving: '2 tbsp (36g)', calories: 52, protein: 0, carbs: 13, fat: 0, fiber: 0, sugar: 10, color: 'yellow' },
  { name: 'Maple Syrup', category: 'Oils & Sauces', serving: '2 tbsp (40ml)', calories: 104, protein: 0, carbs: 27, fat: 0, fiber: 0, sugar: 24, color: 'yellow' },
  { name: 'Honey', category: 'Oils & Sauces', serving: '1 tbsp (21g)', calories: 64, protein: 0, carbs: 17, fat: 0, fiber: 0, sugar: 17, color: 'yellow' },
  { name: 'Guacamole', category: 'Oils & Sauces', serving: '2 tbsp (30g)', calories: 50, protein: 1, carbs: 3, fat: 4, fiber: 2, sugar: 0, color: 'green' },
  { name: 'Pesto Sauce', category: 'Oils & Sauces', serving: '2 tbsp (30g)', calories: 160, protein: 3, carbs: 2, fat: 15, fiber: 1, sugar: 1, color: 'red' },
  { name: 'Marinara Sauce', category: 'Oils & Sauces', serving: '1/2 cup (125g)', calories: 66, protein: 2, carbs: 10, fat: 2, fiber: 2, sugar: 6, color: 'green' },

  // ═══════════════════════ PREPARED / COMMON MEALS ═══════════════════════
  { name: 'Caesar Salad (no chicken)', category: 'Prepared Meals', serving: '2 cups (200g)', calories: 260, protein: 8, carbs: 14, fat: 20, fiber: 2, sugar: 2, color: 'yellow' },
  { name: 'Grilled Chicken Caesar Salad', category: 'Prepared Meals', serving: '1 bowl (350g)', calories: 440, protein: 38, carbs: 14, fat: 26, fiber: 2, sugar: 2, color: 'yellow' },
  { name: 'Garden Salad (no dressing)', category: 'Prepared Meals', serving: '2 cups (150g)', calories: 35, protein: 2, carbs: 7, fat: 0, fiber: 3, sugar: 3, color: 'green' },
  { name: 'Chicken Stir-Fry with Rice', category: 'Prepared Meals', serving: '1 plate (400g)', calories: 480, protein: 32, carbs: 52, fat: 14, fiber: 4, sugar: 5, color: 'yellow' },
  { name: 'Spaghetti Bolognese', category: 'Prepared Meals', serving: '1 plate (400g)', calories: 540, protein: 28, carbs: 60, fat: 18, fiber: 4, sugar: 8, color: 'red' },
  { name: 'Chicken Tikka Masala with Rice', category: 'Prepared Meals', serving: '1 serving (400g)', calories: 560, protein: 30, carbs: 50, fat: 24, fiber: 3, sugar: 6, color: 'red' },
  { name: 'Burrito Bowl', category: 'Prepared Meals', serving: '1 bowl (450g)', calories: 510, protein: 28, carbs: 54, fat: 18, fiber: 10, sugar: 4, color: 'yellow' },
  { name: 'Turkey Sandwich', category: 'Prepared Meals', serving: '1 sandwich (280g)', calories: 380, protein: 28, carbs: 36, fat: 14, fiber: 4, sugar: 5, color: 'yellow' },
  { name: 'BLT Sandwich', category: 'Prepared Meals', serving: '1 sandwich (240g)', calories: 410, protein: 18, carbs: 34, fat: 22, fiber: 2, sugar: 4, color: 'yellow' },
  { name: 'Grilled Cheese Sandwich', category: 'Prepared Meals', serving: '1 sandwich (170g)', calories: 440, protein: 16, carbs: 36, fat: 26, fiber: 2, sugar: 4, color: 'red' },
  { name: 'PB&J Sandwich', category: 'Prepared Meals', serving: '1 sandwich (190g)', calories: 376, protein: 13, carbs: 50, fat: 16, fiber: 4, sugar: 18, color: 'yellow' },
  { name: 'Veggie Burger', category: 'Prepared Meals', serving: '1 burger with bun (200g)', calories: 370, protein: 22, carbs: 38, fat: 14, fiber: 6, sugar: 6, color: 'yellow' },
  { name: 'Cheeseburger', category: 'Prepared Meals', serving: '1 burger (250g)', calories: 540, protein: 28, carbs: 36, fat: 30, fiber: 2, sugar: 7, color: 'red' },
  { name: 'Beef Tacos (2)', category: 'Prepared Meals', serving: '2 tacos (240g)', calories: 410, protein: 22, carbs: 32, fat: 22, fiber: 4, sugar: 3, color: 'yellow' },
  { name: 'Fish Tacos (2)', category: 'Prepared Meals', serving: '2 tacos (240g)', calories: 380, protein: 24, carbs: 30, fat: 18, fiber: 3, sugar: 2, color: 'yellow' },
  { name: 'Chicken Quesadilla', category: 'Prepared Meals', serving: '1 quesadilla (220g)', calories: 490, protein: 30, carbs: 34, fat: 24, fiber: 2, sugar: 2, color: 'yellow' },
  { name: 'Pizza Margherita (2 slices)', category: 'Prepared Meals', serving: '2 slices (224g)', calories: 520, protein: 22, carbs: 60, fat: 20, fiber: 3, sugar: 7, color: 'red' },
  { name: 'Pepperoni Pizza (2 slices)', category: 'Prepared Meals', serving: '2 slices (228g)', calories: 596, protein: 24, carbs: 58, fat: 28, fiber: 3, sugar: 7, color: 'red' },
  { name: 'Mac and Cheese', category: 'Prepared Meals', serving: '1 cup (200g)', calories: 380, protein: 14, carbs: 42, fat: 17, fiber: 2, sugar: 4, color: 'red' },
  { name: 'Fried Rice', category: 'Prepared Meals', serving: '1 cup (200g)', calories: 238, protein: 6, carbs: 34, fat: 9, fiber: 1, sugar: 1, color: 'yellow' },
  { name: 'Pad Thai', category: 'Prepared Meals', serving: '1 plate (350g)', calories: 510, protein: 20, carbs: 62, fat: 20, fiber: 3, sugar: 12, color: 'red' },
  { name: 'Chicken Noodle Soup', category: 'Prepared Meals', serving: '1 cup (248g)', calories: 62, protein: 3, carbs: 9, fat: 2, fiber: 1, sugar: 1, color: 'green' },
  { name: 'Tomato Soup', category: 'Prepared Meals', serving: '1 cup (248g)', calories: 74, protein: 2, carbs: 16, fat: 1, fiber: 1, sugar: 10, color: 'green' },
  { name: 'Miso Soup', category: 'Prepared Meals', serving: '1 cup (240ml)', calories: 40, protein: 3, carbs: 5, fat: 1, fiber: 1, sugar: 2, color: 'green' },
  { name: 'Chili (beef)', category: 'Prepared Meals', serving: '1 cup (253g)', calories: 287, protein: 17, carbs: 22, fat: 14, fiber: 6, sugar: 4, color: 'yellow' },
  { name: 'Scrambled Eggs (2)', category: 'Prepared Meals', serving: '2 eggs (122g)', calories: 182, protein: 12, carbs: 2, fat: 14, fiber: 0, sugar: 2, color: 'yellow' },
  { name: 'Omelette (veggie)', category: 'Prepared Meals', serving: '3-egg (210g)', calories: 280, protein: 22, carbs: 6, fat: 20, fiber: 2, sugar: 2, color: 'yellow' },
  { name: 'Avocado Toast (2 slices)', category: 'Prepared Meals', serving: '2 slices (200g)', calories: 380, protein: 10, carbs: 38, fat: 22, fiber: 8, sugar: 2, color: 'yellow' },
  { name: 'Acai Bowl', category: 'Prepared Meals', serving: '1 bowl (350g)', calories: 420, protein: 8, carbs: 72, fat: 12, fiber: 8, sugar: 48, color: 'yellow' },
  { name: 'Overnight Oats', category: 'Prepared Meals', serving: '1 jar (300g)', calories: 350, protein: 14, carbs: 48, fat: 12, fiber: 6, sugar: 16, color: 'yellow' },
  { name: 'Pancakes with Syrup (3)', category: 'Prepared Meals', serving: '3 pancakes (230g)', calories: 520, protein: 12, carbs: 80, fat: 18, fiber: 2, sugar: 32, color: 'red' },
  { name: 'French Toast (2 slices)', category: 'Prepared Meals', serving: '2 slices (180g)', calories: 380, protein: 12, carbs: 44, fat: 18, fiber: 2, sugar: 16, color: 'yellow' },
  { name: 'Waffles (2)', category: 'Prepared Meals', serving: '2 waffles (142g)', calories: 410, protein: 10, carbs: 56, fat: 16, fiber: 2, sugar: 8, color: 'red' },
  { name: 'Sushi (California Roll, 8 pc)', category: 'Prepared Meals', serving: '8 pieces (220g)', calories: 290, protein: 9, carbs: 48, fat: 6, fiber: 3, sugar: 8, color: 'yellow' },
  { name: 'Ramen (pork broth)', category: 'Prepared Meals', serving: '1 bowl (500g)', calories: 510, protein: 22, carbs: 58, fat: 20, fiber: 2, sugar: 3, color: 'red' },
  { name: 'Pho (beef)', category: 'Prepared Meals', serving: '1 bowl (600g)', calories: 430, protein: 24, carbs: 52, fat: 12, fiber: 2, sugar: 4, color: 'yellow' },
  { name: 'Bibimbap', category: 'Prepared Meals', serving: '1 bowl (500g)', calories: 510, protein: 28, carbs: 58, fat: 18, fiber: 5, sugar: 6, color: 'yellow' },
  { name: 'Mediterranean Salad', category: 'Prepared Meals', serving: '1 bowl (300g)', calories: 320, protein: 12, carbs: 24, fat: 20, fiber: 6, sugar: 5, color: 'green' },
  { name: 'Cobb Salad', category: 'Prepared Meals', serving: '1 bowl (400g)', calories: 520, protein: 38, carbs: 14, fat: 36, fiber: 4, sugar: 4, color: 'yellow' },
  { name: 'Buffalo Wings (6)', category: 'Prepared Meals', serving: '6 wings (240g)', calories: 480, protein: 34, carbs: 2, fat: 36, fiber: 0, sugar: 0, color: 'red' },
  { name: 'French Fries (medium)', category: 'Prepared Meals', serving: '1 serving (117g)', calories: 365, protein: 4, carbs: 44, fat: 19, fiber: 4, sugar: 0, color: 'red' },
  { name: 'Baked Potato (with butter)', category: 'Prepared Meals', serving: '1 medium (213g)', calories: 278, protein: 5, carbs: 42, fat: 11, fiber: 4, sugar: 3, color: 'yellow' },
  { name: 'Mashed Potatoes', category: 'Prepared Meals', serving: '1 cup (210g)', calories: 237, protein: 4, carbs: 36, fat: 9, fiber: 3, sugar: 3, color: 'yellow' },
  { name: 'Roasted Vegetables', category: 'Prepared Meals', serving: '1 cup (180g)', calories: 120, protein: 3, carbs: 16, fat: 5, fiber: 4, sugar: 6, color: 'green' },
  { name: 'Steamed Rice & Tofu', category: 'Prepared Meals', serving: '1 bowl (350g)', calories: 340, protein: 16, carbs: 48, fat: 8, fiber: 3, sugar: 2, color: 'green' },
  { name: 'Shakshuka', category: 'Prepared Meals', serving: '1 serving (350g)', calories: 390, protein: 22, carbs: 28, fat: 22, fiber: 6, sugar: 10, color: 'yellow' },
  { name: 'Falafel Wrap', category: 'Prepared Meals', serving: '1 wrap (280g)', calories: 480, protein: 16, carbs: 52, fat: 22, fiber: 6, sugar: 4, color: 'yellow' },
  { name: 'Greek Salad', category: 'Prepared Meals', serving: '1 bowl (300g)', calories: 280, protein: 8, carbs: 12, fat: 22, fiber: 3, sugar: 5, color: 'green' },
  { name: 'Minestrone Soup', category: 'Prepared Meals', serving: '1 cup (240ml)', calories: 120, protein: 5, carbs: 21, fat: 2, fiber: 5, sugar: 5, color: 'green' },
  { name: 'Lentil Soup', category: 'Prepared Meals', serving: '1 cup (240ml)', calories: 160, protein: 9, carbs: 28, fat: 1, fiber: 8, sugar: 3, color: 'green' },
  { name: 'Clam Chowder', category: 'Prepared Meals', serving: '1 cup (240ml)', calories: 201, protein: 8, carbs: 18, fat: 11, fiber: 1, sugar: 2, color: 'yellow' },

  // ═══════════════════════ DESSERTS & SWEETS ═══════════════════════
  { name: 'Chocolate Chip Cookie', category: 'Desserts', serving: '1 large (40g)', calories: 188, protein: 2, carbs: 26, fat: 9, fiber: 1, sugar: 16, color: 'red' },
  { name: 'Brownie', category: 'Desserts', serving: '1 piece (56g)', calories: 227, protein: 3, carbs: 36, fat: 9, fiber: 1, sugar: 24, color: 'red' },
  { name: 'Vanilla Ice Cream', category: 'Desserts', serving: '1/2 cup (66g)', calories: 137, protein: 2, carbs: 16, fat: 7, fiber: 0, sugar: 14, color: 'red' },
  { name: 'Frozen Yogurt', category: 'Desserts', serving: '1/2 cup (72g)', calories: 110, protein: 3, carbs: 22, fat: 1, fiber: 0, sugar: 18, color: 'yellow' },
  { name: 'Banana (frozen bar)', category: 'Desserts', serving: '1 bar (95g)', calories: 160, protein: 2, carbs: 26, fat: 6, fiber: 2, sugar: 16, color: 'yellow' },
  { name: 'Cheesecake', category: 'Desserts', serving: '1 slice (125g)', calories: 401, protein: 7, carbs: 32, fat: 28, fiber: 0, sugar: 22, color: 'red' },
  { name: 'Apple Pie', category: 'Desserts', serving: '1 slice (155g)', calories: 411, protein: 4, carbs: 58, fat: 19, fiber: 3, sugar: 25, color: 'red' },
  { name: 'Donut (glazed)', category: 'Desserts', serving: '1 donut (60g)', calories: 269, protein: 4, carbs: 31, fat: 15, fiber: 1, sugar: 13, color: 'red' },
  { name: 'Muffin (blueberry)', category: 'Desserts', serving: '1 large (110g)', calories: 385, protein: 6, carbs: 54, fat: 16, fiber: 2, sugar: 28, color: 'red' },
  { name: 'Chocolate Bar (Milk)', category: 'Desserts', serving: '1 bar (44g)', calories: 235, protein: 3, carbs: 26, fat: 13, fiber: 1, sugar: 23, color: 'red' },
  { name: 'Gummy Bears', category: 'Desserts', serving: '1 packet (40g)', calories: 140, protein: 3, carbs: 32, fat: 0, fiber: 0, sugar: 22, color: 'red' },
  { name: 'M&Ms (peanut)', category: 'Desserts', serving: '1 bag (49g)', calories: 243, protein: 5, carbs: 29, fat: 12, fiber: 2, sugar: 24, color: 'red' },

  // ═══════════════════════ FAST FOOD ═══════════════════════
  { name: 'McDonald\'s Big Mac', category: 'Fast Food', serving: '1 burger (212g)', calories: 590, protein: 25, carbs: 46, fat: 34, fiber: 3, sugar: 9, color: 'red' },
  { name: 'McDonald\'s Chicken McNuggets (10pc)', category: 'Fast Food', serving: '10 pieces (162g)', calories: 420, protein: 25, carbs: 25, fat: 25, fiber: 1, sugar: 0, color: 'red' },
  { name: 'McDonald\'s Egg McMuffin', category: 'Fast Food', serving: '1 sandwich (137g)', calories: 300, protein: 17, carbs: 30, fat: 12, fiber: 2, sugar: 3, color: 'yellow' },
  { name: 'McDonald\'s McFlurry (Oreo)', category: 'Fast Food', serving: '1 regular (283g)', calories: 510, protein: 11, carbs: 80, fat: 17, fiber: 1, sugar: 63, color: 'red' },
  { name: 'Subway 6" Turkey Breast', category: 'Fast Food', serving: '1 sub (232g)', calories: 260, protein: 18, carbs: 40, fat: 4, fiber: 5, sugar: 6, color: 'green' },
  { name: 'Subway 6" Italian BMT', category: 'Fast Food', serving: '1 sub (243g)', calories: 380, protein: 17, carbs: 42, fat: 16, fiber: 5, sugar: 6, color: 'yellow' },
  { name: 'Chick-fil-A Chicken Sandwich', category: 'Fast Food', serving: '1 sandwich (170g)', calories: 440, protein: 28, carbs: 40, fat: 19, fiber: 2, sugar: 6, color: 'yellow' },
  { name: 'Chick-fil-A Nuggets (8pc)', category: 'Fast Food', serving: '8 pieces (113g)', calories: 250, protein: 27, carbs: 11, fat: 11, fiber: 0, sugar: 1, color: 'yellow' },
  { name: 'Chipotle Burrito Bowl', category: 'Fast Food', serving: '1 bowl (510g)', calories: 665, protein: 36, carbs: 72, fat: 24, fiber: 14, sugar: 6, color: 'yellow' },
  { name: 'Starbucks Caramel Frappuccino', category: 'Fast Food', serving: 'Grande (473ml)', calories: 380, protein: 5, carbs: 57, fat: 16, fiber: 0, sugar: 52, color: 'red' },
  { name: 'Starbucks Iced Americano', category: 'Fast Food', serving: 'Grande (473ml)', calories: 15, protein: 1, carbs: 2, fat: 0, fiber: 0, sugar: 0, color: 'green' },
  { name: 'In-N-Out Cheeseburger', category: 'Fast Food', serving: '1 burger (268g)', calories: 480, protein: 22, carbs: 39, fat: 27, fiber: 3, sugar: 10, color: 'red' },
  { name: 'Taco Bell Crunchy Taco', category: 'Fast Food', serving: '1 taco (78g)', calories: 170, protein: 8, carbs: 13, fat: 10, fiber: 3, sugar: 1, color: 'yellow' },
  { name: 'Wendy\'s Baconator', category: 'Fast Food', serving: '1 burger (329g)', calories: 950, protein: 57, carbs: 38, fat: 62, fiber: 2, sugar: 9, color: 'red' },
  { name: 'Panera Bread Bowl Soup', category: 'Fast Food', serving: '1 bread bowl (500g)', calories: 620, protein: 22, carbs: 82, fat: 22, fiber: 4, sugar: 6, color: 'red' },
  { name: 'Sweetgreen Harvest Bowl', category: 'Fast Food', serving: '1 bowl (450g)', calories: 590, protein: 22, carbs: 54, fat: 32, fiber: 8, sugar: 14, color: 'yellow' },
];

// Build category list for browsing
const FOOD_CATEGORIES = [...new Set(FOOD_DB.map(f => f.category))];

module.exports = { FOOD_DB, FOOD_CATEGORIES };
